spring:
  data:
      postgres:
        host: localhost
        port: 5432
        username: postgres
        password: root
        database: pokemon

logging:
  level:
    org:
      hibernate:
        type: debug